module.exports = {
  BOOK_DAY_NEAREST: 3,
  BOOK_DAY_FARTHEST: 9,
  // inclusive
  BOOK_HOUR_START: 8,
  BOOK_HOUR_END: 21,
  BOOK_MAX_SELECT: 4,
  B116ROOMS: ['大厅', '沙发室A', '沙发室B', '沙发室C'],
  TRANSLATION: {
    'Network Error': '网络可能开了小差。。',
    'Fatal Error': '服务器不听话了，可通过问题反馈渠道告诉管理员',
    Unauthorized: '登录信息无效或过期',
    'Logged In': '成功登录',
    'Vercode Sent': '验证码已发送至北大邮箱！',
    'Get Code First': '请先获取验证码',
    'Invalid Student ID': '学号打错了？',
    'Please log in to access this page.': '请先登录',
    'User Not Found': '学号输入错误。如确认无误，请通过问题反馈渠道联系管理员',
    'Mail not sent': '服务器出错，验证邮件发送失败',
    'Cookie Expired': '无法获取验证码，请重新登录',
    'Room Out of Range': '选择的教室超出预约范围',
    'Invalid Time': '选择的时间超出预约范围',
    Duplicate: '参与预约的同学不能重复',
    'Sponsor Exceed': '你当前的预约数量已超出上限，请取消不需要的预约',
    'Invitee Exceed': '被邀请人的预约数量已超出上限，换个同学试试吧',
    EXPIRED: '操作超时',
    CANCELED: '已经被取消',
    'Verification Code Error': '验证码错误或过期',
    'NO BOOK_ID': '找不到这条预约',
    'This field is required.': '请确认已填写完整',
    'HAND TOO SLOW': '手太慢啦，预约时间段已经被别人抢走啦！',
    'Name cannot be a number': '姓名不能设置为数字',
    'Name length invalid': '姓名的长度错误',
    'Sponsor too long': '发起人太长了',
    'Not a phone number': '电话号码格式错误',
    'Students too few': '参与学生太少了',
    'Description too long': '描述太长了（256字以内）'
  }
}
